### ISSUE TITLE
Welcome to blockchain page

### ISSUE THREAD

**Issue by MescalitoSpirit** [lotuscommunity/website#12]
Welcome to blockchain page:
[Welcome to Blockchain.docx](https://github.com/user-attachments/files/17079020/Welcome.to.Blockchain.docx)

3 buttons at the bottom of the page (as in "move with us" page):
- Path to the Present
- Web2 vs Web3
- Tracking the future

Web2 vs Web3 page:
[Web 2 vs Web 3.docx](https://github.com/user-attachments/files/17079035/Web.2.vs.Web.3.docx)

**Comment by FabienBradmetz** [comment]
Add web2 us web3 in menu nav bar ?
